stages:
- build
- test

before_script:
  - mkdir -p build

build:
  stage: build
  script:
    - cd build && cmake .. && make
  # use the artifact keyword here to save the build directory in a zip archive uploaded on gitlab
  artifacts:
    name:  heatExecutable
    paths:
        - build/
        
test:
  stage: test
  script:
    - cd build && ctest
