stages:
- build
- test

cache:
  # define what you want to save in your cache here, see for example the untracked keyword
  key: binaries-cache
  paths:
    - build/


build:
  stage: build
  script:
    - cmake . && make

test:
  stage: test
  script:
    - ctest