extends: .gitlab-ci.yml

linux-gcc:
  variables:
    CC: gcc
  <<: *build_test_script
  # fill this part using the build_test_script macro with anchors <<: *build_test_script and variables (to set gcc)
