stages:
- build
- test

before_script:
  - mkdir -p build

build:
  # use the artifact keyword here to save the build directory in a zip archive uploaded on gitlab
  stage: build
  script:
    - cd build && cmake .. && make
  artifacts:
    untracked: false
    when: on_success
    expire_in: "30 days"
    paths:
      - build

test:
  stage: test
  script:
    - cd build && ctest