default:
  image: tthor/heat
  tags: ['docker']

stages:
  - build
  - test

cache:
  key: binaries-cache
  paths:
    - build/

  # define what you want to save in 
  #your cache here, 
  #see for example the untracked keyword

build:
  stage: build
  script:
    - cd build && cmake .. && make
  cache:

test:
  stage: test
  script:
    - cd build  && ctest
    