.build_test_script: &build_test_script
  script:
    - cmake .
    - make
    - ctest

linux-gcc:
  # fill this part using the build_test_script macro with anchors <<: *build_test_script and variables (to set gcc)
  variables:
    CC: gcc
    CXX: g++
  <<: *build_test_script

linux-clang:
  # fill this part using the build_test_script macro with anchors <<: *build_test_script and variables (to set clang)
  variables:
    CC: clang
    CXX: clang++
  <<: *build_test_script
