default:
  image: tthor/heat
  tags: ['docker']

stages:
  - build
  - test
  - deploy

before_script:
  - mkdir -p build

build:
  stage: build
  script:
    - cd build && cmake .. -DCMAKE_C_FLAGS="--coverage".
  artifacts:
    untracked: false
    when: on_success
    paths:
      - build

test:
  stage: test
  script:
    - cd build && ctest
    - gcovr -r ..
  # fix for gcovr
  # add coverage and artifacts

documentation:
  stage: deploy
  script: 
     - cmake . -DHEAT_DOC=ON
     - make doc
  # fill to allow failure of this job without making the pipeline in a failure state
  allow_failure: true
  # fill with the when keyword to be able to trigger this job manually
  when: manual
  # fill with the only and changes keywords to enable this only if some files *.c or *.h change or files in the doc/ directory
  rules:
    - changes:
        - /*.c
        - /*.h
        - /doc/*

