default:
  image: tthor/heat
  tags: ['docker']

.build_test_script: &build_test_script
  script:
    - cmake .
    - make
    - ctest

build:
  extends: .build_test_script
  # fill here the parallel matrix configuration to get the 4 combinations of compilers
  parallel:
    matrix:
        - CC: [gcc, clang]
          CXX: [g++, clang++]
