   default:
     image: tthor/heat
     tags: ['docker']

   .build_test_script: &build_test_script
     script:
       - cmake .
       - make
       - ctest

   build:
     extends: .build_test_script
     parallel:
       matrix:
         - CC: [gcc, clang]
           CXX: [g++, clang++]
