   stages:
   - build
   - test
   - other

   build:
     stage: build
     script:
       - cmake . && make

   test:
     stage: test
     script:
       - cmake . && make && ctest

   documentation:
     stage: other
     script:
       - cmake . -DHEAT_DOC=ON && make doc