default:
  image: tthor/heat
  tags: ['docker']

stages:
  - build
  - test

  # define what you want to save in 
  #your cache here, 
  #see for example the untracked keyword

build:
  stage: build
  script:
    - cmake . && make
  cache:

test:
  stage: test
  script:
    - ctest