linux-gcc:
  variables:
    CC: gcc
    CXX: g++
  script:
    - cmake .
    - make
    - ctest

linux-clang:
  variables:
    CC: clang
    CXX: clang++
  script:
    - cmake .
    - make
    - ctest
    
  