default:
  image: tthor/heat
  tags: ['docker']

stages:
  - build
  - test
  - deploy

before_script:
  - mkdir -p build

build:
  stage: build
  script:
    - cd build && cmake .. -DCMAKE_C_FLAGS="--coverage" && make
  artifacts:
    untracked: false
    when: on_success
    paths:
      - build

test:
  stage: test
  script:
    - cd build 
    - ctest --no-compress-output -T Test -V
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
    - xsltproc -o report.xml ../tools/ctest-to-junit.xsl Testing/**/Test.xml
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml
      junit: build/report.xml
  # fix for gcovr
  # add coverage and artifacts

documentation:
  stage: deploy
  script: 
     - cmake . -DHEAT_DOC=ON
     - make doc
  # fill to allow failure of this job without making the pipeline in a failure state
  allow_failure: true
  # fill with the when keyword to be able to trigger this job manually
  when: manual
  # fill with the only and changes keywords to enable this only if some files *.c or *.h change or files in the doc/ directory
  rules:
    - changes:
        - /*.c
        - /*.h
        - /doc/*

