.build_test_script: &build_test_script
  script:
    - cmake .
    - make
    - ctest

linux-gcc:
  variables:
    CC: gcc
  <<: build_test_script
  # fill this part using the build_test_script macro with anchors <<: *build_test_script and variables (to set gcc)

linux-clang:
  variables:
    CC: clang
  <<: build_test_script
  # fill this part using the build_test_script macro with anchors <<: *build_test_script and variables (to set clang)